name: dalao_client
description: 大佬论坛 dalao.net 客户端
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.4
  intl: ^0.19.0
  html: ^0.15.6
  webview_flutter_platform_interface: ^2.10.0
  webview_windows: ^0.4.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
